"""Seed 150 noise memories for harder benchmark."""
import asyncio
import sys

NOISE = [
    # Finance (20)
    'The Federal Reserve raised interest rates by 25 basis points in March 2024.',
    'Bitcoin reached an all-time high of $73,000 in March 2024.',
    'The S&P 500 index returned 26.3% in 2023, its best year since 2019.',
    'Dollar-cost averaging reduces the impact of volatility on large purchases.',
    'The yield curve inverted in July 2022, historically a recession indicator.',
    'Compound interest formula: A = P(1 + r/n)^(nt) where P is principal.',
    'The SEC approved spot Bitcoin ETFs in January 2024.',
    'Warren Buffett recommends index funds for most individual investors.',
    'The Euro to USD exchange rate averaged 1.08 in 2023.',
    'Hedge funds charge a typical fee structure of 2% management and 20% performance.',
    'Treasury bills are considered the risk-free rate in financial models.',
    'The Black-Scholes model prices European options using five key variables.',
    'SWIFT handles approximately 42 million financial messages per day.',
    'The VIX index measures expected market volatility over 30 days.',
    'ESG investing grew to $35 trillion in assets under management globally.',
    'The London Interbank Offered Rate (LIBOR) was replaced by SOFR in 2023.',
    'Municipal bonds offer tax-exempt interest income for US investors.',
    'The price-to-earnings ratio of the S&P 500 averaged 20.5 in 2023.',
    'Venture capital firms typically expect 10x returns on successful investments.',
    'The FDIC insures bank deposits up to $250,000 per depositor per institution.',
    # Science (20)
    'The speed of light in vacuum is approximately 299,792,458 meters per second.',
    'DNA contains four nucleotide bases: adenine, thymine, guanine, and cytosine.',
    'The human genome contains approximately 3.2 billion base pairs.',
    'Quantum entanglement allows particles to be correlated regardless of distance.',
    'Photosynthesis converts carbon dioxide and water into glucose using sunlight.',
    'The Higgs boson was experimentally confirmed at CERN in 2012.',
    'Mitochondria are the powerhouses of the cell, producing ATP via oxidative phosphorylation.',
    'The observable universe has a diameter of approximately 93 billion light-years.',
    'CRISPR-Cas9 allows precise editing of DNA sequences in living organisms.',
    'Newtons third law states every action has an equal and opposite reaction.',
    'The periodic table contains 118 confirmed elements as of 2024.',
    'Black holes form when massive stars collapse under their own gravity.',
    'The pH scale ranges from 0 (most acidic) to 14 (most basic).',
    'Antibiotics work by disrupting bacterial cell wall synthesis or protein production.',
    'The Doppler effect causes the frequency of waves to change with relative motion.',
    'Entropy in a closed system always increases according to the second law of thermodynamics.',
    'Neurons communicate via electrical impulses and chemical neurotransmitters.',
    'The Krebs cycle occurs in the mitochondrial matrix and produces electron carriers.',
    'Plate tectonics describes the movement of Earths lithospheric plates.',
    'Stem cells can differentiate into specialized cell types in the body.',
    # Cooking (15)
    'Maillard reaction occurs between amino acids and reducing sugars at high temperatures.',
    'Sourdough bread requires a starter culture of wild yeast and lactobacillus bacteria.',
    'Sous vide cooking maintains precise water temperature for consistent results.',
    'Emulsification combines oil and water using an emulsifier like egg yolk lecithin.',
    'Caramelization begins at 320F (160C) when sugar molecules break down.',
    'Fermentation converts sugars to alcohol or organic acids using microorganisms.',
    'A roux is made by cooking equal parts flour and fat as a thickening agent.',
    'Blanching vegetables in boiling water preserves color and reduces enzyme activity.',
    'Gluten develops when wheat flour proteins glutenin and gliadin are hydrated.',
    'The smoke point of extra virgin olive oil is approximately 375F (190C).',
    'Brining meat in saltwater solution improves moisture retention during cooking.',
    'Deglazing a pan with wine or stock dissolves flavorful browned bits (fond).',
    'Tempering chocolate involves heating and cooling to stabilize cocoa butter crystals.',
    'Umami is the fifth basic taste, associated with glutamate and nucleotides.',
    'Cold fermentation of pizza dough for 72 hours develops complex flavors.',
    # Sports (15)
    'The marathon distance of 26.2 miles was standardized at the 1908 London Olympics.',
    'Usain Bolt holds the 100m world record at 9.58 seconds set in 2009.',
    'The FIFA World Cup is held every four years and attracts billions of viewers.',
    'A regulation NBA basketball court is 94 feet long and 50 feet wide.',
    'The Tour de France covers approximately 3,500 kilometers over 21 stages.',
    'Tennis uses a scoring system of 15, 30, 40, and game within each set.',
    'The Elo rating system was originally designed for chess player rankings.',
    'Olympic swimming pools are 50 meters long and contain 8 lanes.',
    'A hat trick in hockey refers to scoring three goals in a single game.',
    'The Boston Marathon is the oldest annual marathon, first held in 1897.',
    'Cricket test matches can last up to five days with two innings per side.',
    'Formula 1 cars generate enough downforce to theoretically drive upside down.',
    'The NBA three-point line is 23 feet 9 inches from the basket.',
    'Kipchoge broke the two-hour marathon barrier in 2019 with 1:59:40.',
    'The offside rule in soccer prevents attackers from cherry-picking near goal.',
    # History (15)
    'The Roman Empire reached its greatest territorial extent under Emperor Trajan in 117 AD.',
    'The printing press was invented by Johannes Gutenberg around 1440.',
    'The French Revolution began in 1789 with the storming of the Bastille.',
    'The Silk Road connected China to the Mediterranean for over 1,500 years.',
    'The Industrial Revolution started in Britain in the late 18th century.',
    'The Berlin Wall fell on November 9, 1989, reunifying East and West Germany.',
    'The Rosetta Stone was discovered in 1799 and helped decode Egyptian hieroglyphs.',
    'The Ottoman Empire lasted from 1299 to 1922, spanning three continents.',
    'The Apollo 11 mission landed the first humans on the Moon on July 20, 1969.',
    'The Magna Carta was signed in 1215 limiting the power of the English monarchy.',
    'The Black Death killed an estimated 75-200 million people in the 14th century.',
    'The Renaissance began in Italy in the 14th century and spread across Europe.',
    'The Panama Canal opened in 1914, connecting the Atlantic and Pacific oceans.',
    'The Cold War lasted from 1947 to 1991 between the US and Soviet Union.',
    'Ancient Egypt built the Great Pyramid of Giza around 2560 BC.',
    # Geography (15)
    'The Amazon River is the largest river by discharge volume in the world.',
    'Mount Everest stands at 8,849 meters above sea level in the Himalayas.',
    'The Sahara Desert covers approximately 9.2 million square kilometers.',
    'The Mariana Trench reaches a depth of approximately 11,034 meters.',
    'Australia is both a country and a continent with a population of 26 million.',
    'The Great Barrier Reef stretches over 2,300 kilometers along Australias coast.',
    'Iceland sits on the Mid-Atlantic Ridge where tectonic plates diverge.',
    'Lake Baikal in Siberia contains approximately 20% of the worlds fresh surface water.',
    'The Nile River flows north for 6,650 kilometers through northeastern Africa.',
    'Antarctica is the coldest continent with temperatures reaching minus 89.2 Celsius.',
    'The Ring of Fire encircles the Pacific Ocean with 75% of worlds active volcanoes.',
    'The Dead Sea at 430 meters below sea level is the lowest point on land.',
    'The Amazon rainforest produces approximately 20% of the worlds oxygen.',
    'Greenland is the worlds largest island with an area of 2.16 million square kilometers.',
    'The Strait of Gibraltar is only 14 kilometers wide at its narrowest point.',
    # Music & Art (15)
    'Beethoven composed his Ninth Symphony while almost completely deaf.',
    'The Mona Lisa by Leonardo da Vinci hangs in the Louvre Museum in Paris.',
    'Jazz originated in New Orleans in the late 19th and early 20th centuries.',
    'The piano has 88 keys spanning seven octaves plus a minor third.',
    'Picasso co-founded the Cubist movement in the early 20th century.',
    'A standard orchestra consists of four sections: strings, woodwinds, brass, and percussion.',
    'The blues scale adds a flatted fifth to the minor pentatonic scale.',
    'Vincent van Gogh painted The Starry Night while in an asylum in 1889.',
    'Hip-hop originated in the Bronx, New York City in the 1970s.',
    'The golden ratio (1.618) appears frequently in Renaissance art and architecture.',
    'Impressionism emerged in 1860s Paris with artists like Monet and Renoir.',
    'A vinyl record typically rotates at 33 1/3 or 45 revolutions per minute.',
    'The twelve-bar blues is the most common chord progression in blues music.',
    'Michelangelo painted the Sistine Chapel ceiling between 1508 and 1512.',
    'The electric guitar was first commercially produced in the 1930s.',
    # Software-adjacent distractors (35)
    'React uses a virtual DOM to minimize direct manipulation of the browser DOM.',
    'Python garbage collection uses reference counting with cycle detection.',
    'TCP three-way handshake establishes connections using SYN, SYN-ACK, ACK packets.',
    'MongoDB stores data in flexible JSON-like documents called BSON.',
    'The CAP theorem states distributed systems can guarantee only two of three properties.',
    'Machine learning models are prone to overfitting when trained on small datasets.',
    'GraphQL allows clients to request exactly the data they need in a single query.',
    'Kubernetes pods are the smallest deployable units in a container orchestration system.',
    'TLS 1.3 reduced the handshake from two round trips to one for improved latency.',
    'Bloom filters provide probabilistic set membership testing with no false negatives.',
    'The Linux kernel uses a completely fair scheduler (CFS) for process management.',
    'Git uses SHA-1 hashes to identify commits, trees, and blob objects.',
    'WebAssembly enables near-native performance for web applications.',
    'Prometheus collects time-series metrics using a pull-based model.',
    'The Actor model treats actors as the fundamental unit of concurrent computation.',
    'Consistent hashing minimizes key redistribution when nodes are added or removed.',
    'Apache Kafka uses an append-only commit log for durable message storage.',
    'DNS resolution follows a hierarchical system from root servers to authoritative nameservers.',
    'Redis supports five main data types: strings, lists, sets, sorted sets, and hashes.',
    'The OSI model defines seven layers of network communication abstraction.',
    'Rust prevents data races at compile time through its ownership and borrowing system.',
    'Docker containers share the host kernel unlike traditional virtual machines.',
    'B-trees are the standard data structure for database indexes on disk.',
    'OAuth 2.0 authorization code flow is recommended for server-side applications.',
    'gRPC uses Protocol Buffers for efficient binary serialization of structured data.',
    'Content delivery networks cache static assets at edge locations near users.',
    'The PageRank algorithm measures webpage importance based on incoming link structure.',
    'Microservices communicate through APIs while sharing nothing else.',
    'Load balancers distribute traffic using algorithms like round-robin or least connections.',
    'SQLite is an embedded database that stores the entire database in a single file.',
    'WebSockets provide full-duplex communication channels over a single TCP connection.',
    'The circuit breaker pattern prevents cascading failures in distributed systems.',
    'Raft consensus algorithm ensures all nodes agree on the same log entries.',
    'Zero-copy networking reduces CPU overhead by avoiding unnecessary memory copies.',
    'QUIC protocol combines transport and encryption into a single handshake.',
]


async def main():
    from ark.local import call_tool
    total = len(NOISE)
    for i, text in enumerate(NOISE):
        r = await call_tool('ingest', {'content': text})
        if (i + 1) % 25 == 0 or i == total - 1:
            print(f'  [{i+1}/{total}] ingested')
    print(f'Done: {total} noise memories seeded')


if __name__ == '__main__':
    asyncio.run(main())
